extend type Query {
    getCreditCards(params: GetCreditCardsInput): GetCreditCardsResponse
    getCreditCardTransactions(params: GetCreditCardTransactionsInput): GetCreditCardTransactionsResponse
    getCreditCardInstallmentDueDates(params: GetInstallmentsDueDatesInput): GetInstallmentsDueDatesResponse
}

# Get credit cards
input GetCreditCardsInput {
    id: String
    active: Boolean
}

type GetCreditCardsResponse {
    quantity: Int!
    creditCards: [CreditCard]!
}

type CreditCard {
    creditCardId: String!
    active: Boolean!
    ownerId: String!
    nickname: String!
    accountId: String
    currencyId: String!
    issueDate: Date
    cancellationDate: String
    dueDay: Int
    closeDay: Int
}

# Credit card transactions
input GetCreditCardTransactionsInput {
    creditCardId: String
    startPeriod: Int
    endPeriod: Int
    parentId: Int
}

type GetCreditCardTransactionsResponse {
    quantity: Int!
    transactions: [CreditCardTransactions]!
}

type CreditCardTransactions {
    id: String!
    creditCardNickname: String
    creditCardId: String!
    period: Int!
    dueDate: Date!
    transactionDate: Date!
    amount: Float!
    categoryId: String!
    categoryName: String
    currencyId: String!
    currencySymbol: String
    transactionCurrencyId: String
    transactionCurrencySymbol: String
    transactionAmount: Float!
    isInstallment: Boolean!
    currentInstallment: Int!
    installments: Int!
    totalAmount: Float
    description: String
    createdAt: DateTime!
    editedAt: DateTime
}


# Credit card installments
input GetInstallmentsDueDatesInput {
    creditCardId: String!
    totInstallments: Int!
    transactionDate: Date!
}

type GetInstallmentsDueDatesResponse {
    dueDates: [InstallmentsDueDates]!
}

type InstallmentsDueDates {
    currentInstallment: Int!
    dueDate: Date!
}