extend type Query {
    getCreditCards(params: GetCreditCardsInput): GetCreditCardsResponse
    getCreditCardTransactions(params: GetCreditCardTransactionsInput): GetCreditCardTransactionsResponse
    getCreditCardMonthlyBill(period: Int!): GetCreditCardMonthlyBillResponse!
    getCreditCardBillHistoricalData(params: GetCreditCardMonthlyBillEvolutionInput): GetCreditCardBillHistoricalDataResponse!
    getCreditCardTransactionMetadataById(id: Int!): GetTransactionMetadataById
    getCreditCardInstallmentDueDates(params: GetInstallmentsDueDatesInput): GetInstallmentsDueDatesResponse
}

extend type Mutation {
    createCreditCardTransaction(transaction: CreditCardTransactionInput!): CreditCardTransactionResponse!
    updateCreditCardTransaction(transaction: CreditCardTransactionInput!): CreditCardTransactionResponse!

    deleteCreditCardTransaction(id: Int!): DeleteCreditCardTransactionResponse!
}

# Get credit cards
input GetCreditCardsInput {
    id: String
    active: Boolean
}

type GetCreditCardsResponse {
    quantity: Int!
    creditCards: [CreditCard]!
}

type CreditCard {
    creditCardId: String!
    active: Boolean!
    ownerId: String!
    nickname: String!
    accountId: String
    currencyId: String!
    issueDate: Date
    cancellationDate: String
    dueDay: Int
    closeDay: Int
}

# Credit card transactions
input GetCreditCardTransactionsInput {
    creditCardId: String
    startPeriod: Int
    endPeriod: Int
    parentId: Int
}

type GetCreditCardTransactionsResponse {
    quantity: Int!
    transactions: [CreditCardTransaction]!
}

type GetCreditCardTransactionByIdResponse {
    transaction: CreditCardTransaction
}

type CreditCardTransaction {
    id: String!
    ownerId: String!
    creditCardId: String!
    creditCardNickname: String
    period: Int!
    dueDate: Date!
    transactionDate: Date!
    amount: Float!
    categoryId: String!
    categoryName: String
    currencyId: String!
    currencySymbol: String
    transactionCurrencyId: String
    transactionCurrencySymbol: String
    transactionAmount: Float!
    dollarExchangeRate: Float
    currencyDollarExchangeRate: Float
    totalTax: Float
    isInstallment: Boolean!
    currentInstallment: Int!
    installments: Int!
    totalAmount: Float
    parentId: Int
    description: String
    origin: String 
    isValidated: Boolean
    operationType: String
    createdAt: DateTime
    editedAt: DateTime
}

input BillEntryInstallmentInput {
    transactionId: Int
    currentInstallment: Int!
    dueDate: Date!
    amount: Float!
}

type GetTransactionMetadataById {
    transactionMetadata: TransactionMetadata!
}

type TransactionMetadata {
    id: Int!
    creditCardId: String!
    transactionDate: Date
    totalAmount: Float!
    isInstallment: Boolean!
    totalInstallments: Int!
    installments: [BillEntryInstallment!]!
    categoryId: String!
    currencyId: String!
    isInternationalTransaction: Boolean!
    transactionCurrencyId: String
    transactionAmount: Float
    totalTax: Float
    dollarExchangeRate: Float
    currencyDollarExchangeRate: Float
    description: String
}

type BillEntryInstallment {
    transactionId: Int
    currentInstallment: Int!
    dueDate: Date!
    amount: Float!
}

input CreditCardTransactionInput {
    id: Int
    creditCardId: String!
    transactionDate: Date
    totalAmount: Float!
    totalInstallments: Int!
    installments: [BillEntryInstallmentInput!]!
    isInstallment: Boolean!
    categoryId: String!
    currencyId: String!
    isInternationalTransaction: Boolean!
    transactionCurrencyId: String
    transactionAmount: Float
    totalTax: Float
    dollarExchangeRate: Float
    currencyDollarExchangeRate: Float
    description: String
}

type CreditCardTransactionResponse {
    success: Boolean!
    ids: [Int]!
}

type DeleteCreditCardTransactionResponse {
    """
        Whether the delete was successfull
    """
    success: Boolean!
    """
        Amount of transactions deleted, usefull in installments transactions
    """
    transactionCount: Int!
}

type GetCreditCardMonthlyBillResponse {
    bill: [CreditCardMonthlyBill]
}

input GetCreditCardMonthlyBillEvolutionInput {
    startPeriod: Int!
    endPeriod: Int
}

type GetCreditCardBillHistoricalDataResponse {
    historicalData: HistoricalData
}

type HistoricalData {
    periodAverage: Float
    historicalAverage: Float
    goal: Float
    periodRange: [Int]
    historicalData: [JSON]
}

type CreditCardMonthlyBill {
    creditCardId: String!
    creditCardNickname: String!
    period: Int!
    totalAmount: Float!
    quantityTransactions: Int!
    transactions: [CreditCardTransaction]!
}

# Credit card installments
input GetInstallmentsDueDatesInput {
    creditCardId: String!
    totInstallments: Int!
    transactionDate: Date!
}

type GetInstallmentsDueDatesResponse {
    dueDates: [InstallmentsDueDates]!
}

type InstallmentsDueDates {
    currentInstallment: Int!
    dueDate: Date!
}