extend type Query {
    getHelloWorld: String
    getIndexerSeries(params: GetIndexerSeriesInput! ): GetIndexerSeriesResponse
    getCurrencies: GetCurrenciesResponse
    getPeriodicity: GetPeriodicityResponse
}

extend type Mutation {
    _empty: String
}

# Indexer series schemas
input GetIndexerSeriesInput {
    indexerId: String!
    periodicityId: String
    startPeriod: Int
    endPeriod: Int
}

type GetIndexerSeriesResponse {
    quantity: Int!,
    series: [IndexerSeries]
}

type IndexerSeries {
    id: String!
    indexerId: String!
    indexerName: String
    date: String
    period: Int
    value: Float
    periodicityId: String!
    periodicityName: String
    unit: String
}

# Periodicity schemas
type GetPeriodicityResponse {
    quantity: Int!
    periodicities: [Periodicity]!
}

type Periodicity {
    id: String!
    name: String!
    description: String
    order: Int
}

# Currency schemas
type GetCurrenciesResponse {
    quantity: Int!
    currencies: [Currency]!
}

type Currency {
    currencyId: String!
    name: String!
    symbol: String!
}


# Currency dashboard schemas
input GetCurrencyAveragePriceInput {
    currencyId: String!
    startDate: String!
    endDate: String!
}

type GetCurrencyAveragePriceResponse {
    currencyId: String!
    currencySymbol: String!
    averagePrice: Float!

}