# This file contains the schemas for genral Investment functions that aggreagates all
#   investment types

extend type Query {
    getInvestmentPerformance(params: GetInvestmentPerformanceInput): GetInvestmentPerformanceResponse
    getInvestmentStatementById(statement_id: String!): GetInvestmentStatementByIdResponde
    getStatementMetadata(params: GetStatementMetadataInput): GetStatementMetadataResponse
}

extend type Mutation {
    # Investment
    settleInvestment(input: SettleInvestmentInput): SettleInvestmentResponse!

    # Statement
    createInvestmentStatement(statement: CreateInvestmentStatementInput): CreateInvestmentStatementResponse
    updateInvestmentStatement(statement: UpdateInvestmentStatementInput): UpdateInvestmentStatementResponse
}


# Performance Schemas
input GetInvestmentPerformanceInput {
    investmentId: String
}

type GetInvestmentPerformanceResponse {
    xLabel: [String]! 
    data: [LineChartSeries!]!
}


# Investments schemas
input SettleInvestmentInput {
    investmentId: String!
    gross_amount: Float!
    net_amount: Float!
    tax_detail: [TaxFeeDetail]
    fee_detail: [TaxFeeDetail]
    settlement_date: Date!
    settlement_amount: Float!
}

type SettleInvestmentResponse {
    settled: Boolean!
}

#  Statement Schemas
input TaxFeeDetail {
    taxFeeId: String!
    amount: Float!
    currencyId: String!
}

input CreateInvestmentStatementInput {
    investmentId: String!
    period: Int!
    contribution: Float!
    withdrawn: Float!
    referenceDate: Date!
    grossAmount: Float!
    netAmount: Float!
    taxDetail: [TaxFeeDetail]
    feeDedtail: [TaxFeeDetail]
}

type CreateInvestmentStatementResponse {
    created: Boolean!
    statementId: String!
}

input GetInvestmentStatementByIdInput {
    statementId: String!
}

type GetInvestmentStatementByIdResponde {
    statement: Statement!
}

input UpdateInvestmentStatementInput {
    statementId: String!
    contribution: Float
    grossAmount: Float
    netAmount: Float
    taxDetail: [TaxFeeDetail]
    feeDedtail: [TaxFeeDetail]
}

type UpdateInvestmentStatementResponse {
    updated: Boolean!
    statementId: String!
}

input GetStatementMetadataInput {
    investmentId: String!
}

type GetStatementMetadataResponse {
    period: Int!
    referenceDate: Date!
    contribution: Float!
}

type Statement {
    id: String!
    period: Int!
    previousAmount: Float!
    contribution: Float!
    withdraw: Float!
    grossAmount: Float!
    totalTax: Float!
    # tax_detail: list[TaxFeeSchema] | None = Field(
    #     ..., description="The detail of taxes"
    # )
    totalFee: Float!
    # fee_detail: list[TaxFeeSchema] | None = Field(..., description="The detail of fees")
    referenceDate: Date!
    atMaturity: Boolean!
    valueChange: Float!
    percentageChange: Float!
    netAmount: Float!
}