# This file contains the schemas for genral Investment functions that aggreagates all
#   investment types

extend type Query {
    getInvestments(params: GetInvestmentsInput): GetInvestmentsResponse
    getInvestmentById(params: GetInvestmentByIdInput!): GetInvestmentByIdResponse
    
    getInvestmentPerformance(params: GetInvestmentPerformanceInput): GetInvestmentPerformanceResponse
    getInvestmentStatements(params: GetInvestmentStatementsInput): GetInvestmentStatementsResponse
    getInvestmentStatement(params: GetInvestmentStatementInput!): GetInvestmentStatementResponde
    getStatementMetadata(params: GetStatementMetadataInput): GetStatementMetadataResponse

    getInvestmentObjectives(params: GetInvestmentObjectivesInput): GetInvestmentObjectivesResponse
    getInvestmentTypes: GetInvestmentTypesResponse
}

extend type Mutation {
    # Investment
    settleInvestment(input: SettleInvestmentInput): SettleInvestmentResponse!

    # Statement
    createInvestmentStatement(statement: CreateInvestmentStatementInput): CreateInvestmentStatementResponse
    updateInvestmentStatement(statement: UpdateInvestmentStatementInput): UpdateInvestmentStatementResponse
}


# Performance Schemas
input GetInvestmentPerformanceInput {
    investmentId: String
    indexerId: String
    periodRange: Int
    isSettled: Boolean
}

type GetInvestmentPerformanceResponse {
    indexer_name: String!
    xLabel: [Int]!
    data: [ChartSeries]!
}

type ChartSeries {
    data: [Float]!
    label: String!
}

# Investments schemas
input GetInvestmentByIdInput {
    id: String!
}

type GetInvestmentByIdResponse {
    investment: Investment
}

input GetInvestmentsInput {
    id: String
    startDate: String
    endDate: String
    isSettled: Boolean
    investmentTypeId: String
}

type GetInvestmentsResponse {
    quantity: Int!
    investments: [Investment]!
}

type Investment {
    id: String!
    custodianId: String!
    accountId: String
    name: String!
    typeId: String!
    transactionDate: Date!
    maturityDate: String
    quantity: Float!
    price: Float!
    amount: Float!
    contractedRate: String
    currencyId: String!
    currencySymbol: String
    indexerTypeId: String!
    indexerTypeName: String
    indexerId: String!
    indexerName: String
    liquidityId: String!
    liquidityName: String
    isSettled: Boolean!
    settlementDate: String
    settlementAmount: Float
    countryId: String!
    countryName: String
    observation: String
    objectiveId: String
    grossAmount: Float
    totalContribution: Float
    totalWithdrawn: Float
    percentageChange: Float
    isLatestStatementPeriod: Boolean
    latestStatementPeriod: Int
}

input SettleInvestmentInput {
    investmentId: String!
    gross_amount: Float!
    net_amount: Float!
    tax_detail: [TaxFeeDetail]
    fee_detail: [TaxFeeDetail]
    settlement_date: Date!
    settlement_amount: Float!
}

type SettleInvestmentResponse {
    settled: Boolean!
}

#  Statement Schemas
input TaxFeeDetail {
    taxFeeId: String!
    amount: Float!
    currencyId: String!
}

input CreateInvestmentStatementInput {
    id: String
    investmentId: String!
    name: String
    transactionDate: Date
    maturityDate: Date
    referenceDate: Date!
    period: Int!
    contribution: Float!
    withdrawn: Float!
    grossAmount: Float!
    netAmount: Float!
    valueChange: Float
    percentageChange: Float
    taxDetails: [TaxFeeDetail]
    feeDetails: [TaxFeeDetail]
}

type CreateInvestmentStatementResponse {
    created: Boolean!
    statementId: String!
}

"""
Get a list of statements based on filters for a investment
"""
input GetInvestmentStatementsInput {
    investmentId: String!
    startDate: String
    endDate: String
    period: Int
}

type GetInvestmentStatementsResponse {
    quantity: Int!
    statements: [Statement]!
}

"""
Get a single statement by statement ID
"""
input GetInvestmentStatementInput {
    id: String!
}

type GetInvestmentStatementResponde {
    statement: Statement
}

input UpdateInvestmentStatementInput {
    id: String!
    contribution: Float
    withdrawn: Float
    grossAmount: Float
    netAmount: Float
    taxDetail: [TaxFeeDetail]
    feeDedtail: [TaxFeeDetail]
}

type UpdateInvestmentStatementResponse {
    updated: Boolean!
    statementId: String!
}

input GetStatementMetadataInput {
    investmentId: String!
}

type GetStatementMetadataResponse {
    period: Int!
    referenceDate: Date!
    contribution: Float!
    investmentName: String
    investmentTransactionDate: Date
    investmentMaturityDate: Date
}

type Statement {
    id: String!
    investmentId: String!
    period: Int!
    previousAmount: Float!
    contribution: Float!
    withdrawn: Float!
    grossAmount: Float!
    totalTax: Float!
    totalFee: Float!
    referenceDate: Date!
    atMaturity: Boolean!
    currencyId: String!
    valueChange: Float
    percentageChange: Float
    netAmount: Float!
}

input GetInvestmentObjectivesInput {
    id: String
}

type GetInvestmentObjectivesResponse {
    quantity: Int!
    objectives: [InvestmentObjective]!
}

type InvestmentObjective {
    id: String!
    ownerId: String!
    title: String!
    description: String
    currencyId: String!
    currencySymbol: String
    amount: Float!
    currentAmount: Float
    estimateDeadline: Date
}

type GetInvestmentTypesResponse {
    quantity: Int!
    investmentTypes: [InvestmentType]!
}

type InvestmentType {
    id: String!
    name: String!
    description: String
    parentId: String
    investmentCategoryId: String
}
