# This file contains the schemas for genral Investment functions that aggreagates all
#   investment types

extend type Query {
    getInvestments(params: GetInvestmentsInput): GetInvestmentsResponse
    
    getInvestmentPerformance(params: GetInvestmentPerformanceInput): GetInvestmentPerformanceResponse
    getInvestmentStatements(params: GetInvestmentStatementsInput): GetInvestmentStatementsResponse
    getInvestmentStatementById(input: GetInvestmentStatementByIdInput!): GetInvestmentStatementByIdResponde
    getStatementMetadata(params: GetStatementMetadataInput): GetStatementMetadataResponse

    getInvestmentObjectives(params: GetInvestmentObjectivesInput): GetInvestmentObjectivesResponse
}

extend type Mutation {
    # Investment
    settleInvestment(input: SettleInvestmentInput): SettleInvestmentResponse!

    # Statement
    createInvestmentStatement(statement: CreateInvestmentStatementInput): CreateInvestmentStatementResponse
    updateInvestmentStatement(statement: UpdateInvestmentStatementInput): UpdateInvestmentStatementResponse
}


# Performance Schemas
input GetInvestmentPerformanceInput {
    investmentId: String
    indexerId: String
    periodRange: Int
    isSettled: Boolean
}

type GetInvestmentPerformanceResponse {
    indexer_name: String!
    xLabel: [Int]!
    data: [ChartSeries]!
}

type ChartSeries {
    data: [Float]!
    label: String!
}

# Investments schemas
input GetInvestmentsInput {
    investmentId: String
    startDate: String
    endDate: String
    isSettled: Boolean
}

type GetInvestmentsResponse {
    quantity: Int!
    investments: [Investment]!
}

type Investment {
    investmentId: String!
    custodianId: String!
    accountId: String
    name: String!
    investmentTypeId: String!
    transactionDate: Date!
    maturityDate: String
    quantity: Float!
    price: Float!
    amount: Float!
    contractedRate: String
    currencyId: String!
    currencySymbol: String
    indexerTypeId: String!
    indexerTypeName: String
    indexerId: String!
    indexerName: String
    liquidityId: String!
    liquidityName: String
    isSettled: Boolean!
    settlementDate: String
    settlementAmount: Float
    countryId: String!
    countryName: String
    observation: String
    objectiveId: String
    grossAmount: Float!
    totalContribution: Float!
    totalWithdrawn: Float!
    percentageChange: Float!
}


input SettleInvestmentInput {
    investmentId: String!
    gross_amount: Float!
    net_amount: Float!
    tax_detail: [TaxFeeDetail]
    fee_detail: [TaxFeeDetail]
    settlement_date: Date!
    settlement_amount: Float!
}

type SettleInvestmentResponse {
    settled: Boolean!
}

#  Statement Schemas
input TaxFeeDetail {
    taxFeeId: String!
    amount: Float!
    currencyId: String!
}

input CreateInvestmentStatementInput {
    investmentStatementId: String
    investmentId: String!
    name: String
    transactionDate: Date
    maturityDate: Date
    referenceDate: Date!
    period: Int!
    contribution: Float!
    withdrawn: Float!
    grossAmount: Float!
    netAmount: Float!
    valueChange: Float
    percentageChange: Float
    taxDetails: [TaxFeeDetail]
    feeDetails: [TaxFeeDetail]
}

type CreateInvestmentStatementResponse {
    created: Boolean!
    statementId: String!
}

input GetInvestmentStatementsInput {
    investmentId: String!
    startDate: String
    endDate: String
    period: Int
}

type GetInvestmentStatementsResponse {
    quantity: Int!
    statements: [Statement]!
}

input GetInvestmentStatementByIdInput {
    statementId: String!
}

type GetInvestmentStatementByIdResponde {
    statement: Statement!
}

input UpdateInvestmentStatementInput {
    statementId: String!
    contribution: Float
    grossAmount: Float
    netAmount: Float
    taxDetail: [TaxFeeDetail]
    feeDedtail: [TaxFeeDetail]
}

type UpdateInvestmentStatementResponse {
    updated: Boolean!
    statementId: String!
}

input GetStatementMetadataInput {
    investmentId: String!
}

type GetStatementMetadataResponse {
    period: Int!
    referenceDate: Date!
    contribution: Float!
}

type Statement {
    id: String!
    investmentId: String!
    period: Int!
    previousAmount: Float!
    contribution: Float!
    withdrawn: Float!
    grossAmount: Float!
    totalTax: Float!
    totalFee: Float!
    referenceDate: Date!
    atMaturity: Boolean!
    valueChange: Float!
    percentageChange: Float!
    netAmount: Float!
}

input GetInvestmentObjectivesInput {
    id: String
}

type GetInvestmentObjectivesResponse {
    quantity: Int!
    objectives: [InvestmentObjective]!
}

type InvestmentObjective {
    id: String!
    ownerId: String!
    title: String!
    description: String
    currencyId: String!
    currencySymbol: String
    amount: Float!
    currentAmount: Float
    estimateDeadline: Date
}