"""Add earnings to account balance model

Revision ID: 6bb49e4ed134
Revises: c9eb91aef675
Create Date: 2024-09-25 20:48:10.487387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb49e4ed134'
down_revision: Union[str, None] = 'c9eb91aef675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_balance', sa.Column('earnings', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_balance', 'earnings')
    # ### end Alembic commands ###
