"""Add null to operation_type in account transaction model

Revision ID: 7f6e0b27c1d7
Revises: efda8c07479c
Create Date: 2024-11-11 20:15:39.622251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f6e0b27c1d7"
down_revision: Union[str, None] = "efda8c07479c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account_transaction",
        "operation_type",
        existing_type=sa.VARCHAR(length=15),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account_transaction",
        "operation_type",
        existing_type=sa.VARCHAR(length=15),
        nullable=False,
    )
    # ### end Alembic commands ###
