"""Remove balance model

Revision ID: d9ad938959f5
Revises: 6aa0a32c70ab
Create Date: 2024-09-25 13:32:34.082617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ad938959f5'
down_revision: Union[str, None] = '6aa0a32c70ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balance',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('incoming', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('outgoing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transactions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='account_balance_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_balance_pkey')
    )
    # ### end Alembic commands ###
