"""Add investment statement model

Revision ID: ee073f875441
Revises: 3055c378ec5c
Create Date: 2024-09-30 20:18:57.902045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee073f875441'
down_revision: Union[str, None] = '3055c378ec5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_statement',
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_amount', sa.Float(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('total_tax', sa.Float(), nullable=False),
    sa.Column('total_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('tax_detail', sa.JSON(), nullable=True),
    sa.Column('fee_detail', sa.JSON(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('at_maturity', sa.Boolean(), nullable=False),
    sa.Column('value_change', sa.Float(), nullable=True),
    sa.Column('percentage_change', sa.Float(), nullable=True),
    sa.Column('index_change', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_statement')
    # ### end Alembic commands ###
