"""Remove null fro mrequired fields

Revision ID: 54705e7241bc
Revises: 254ce0707deb
Create Date: 2024-12-10 11:13:11.383538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '54705e7241bc'
down_revision: Union[str, None] = '254ce0707deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_transaction', 'category_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.drop_column('account_transaction', 'category_id_old')
    op.alter_column('credit_card_transaction', 'category_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.drop_column('credit_card_transaction', 'category_id_old')
    op.alter_column('investment', 'account_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('investment_statement', 'reference_date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.add_column('investment_type', sa.Column('country_id', sa.String(length=5), nullable=True))
    op.create_foreign_key(None, 'investment_type', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_type', type_='foreignkey')
    op.drop_column('investment_type', 'country_id')
    op.alter_column('investment_statement', 'reference_date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.alter_column('investment', 'account_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.add_column('credit_card_transaction', sa.Column('category_id_old', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('credit_card_transaction', 'category_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.add_column('account_transaction', sa.Column('category_id_old', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('account_transaction', 'category_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
