"""Change field name from description to observation in investment model

Revision ID: 5fcb9554b4e5
Revises: 7456a1c0d5b2
Create Date: 2024-12-04 15:01:56.881384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fcb9554b4e5"
down_revision: Union[str, None] = "7456a1c0d5b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment", sa.Column("observation", sa.String(length=200), nullable=True)
    )
    op.drop_column("investment", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment",
        sa.Column(
            "description", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("investment", "observation")
    # ### end Alembic commands ###
