"""Remove indexer series model

Revision ID: 8cb5acfd36f3
Revises: 5b832f2055b6
Create Date: 2024-10-18 21:26:19.711253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8cb5acfd36f3"
down_revision: Union[str, None] = "5b832f2055b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("indexer_series")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexer_series",
        sa.Column("indexer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "indexer_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("period", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("periodicity_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "periodicity_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("unit", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "edited_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("edited_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["indexer_id"], ["indexer.id"], name="indexer_series_indexer_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["periodicity_id"],
            ["periodicity.id"],
            name="indexer_series_periodicity_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="indexer_series_pkey"),
    )
    # ### end Alembic commands ###
