"""Change type for float field in account and investment models

Revision ID: ed2065ffe236
Revises: 22cec460c931
Create Date: 2024-10-31 14:17:30.321532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed2065ffe236"
down_revision: Union[str, None] = "22cec460c931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account_transaction",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "account_transaction",
        "transaction_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "account_transaction",
        "exchange_rate",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "perc_tax",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=10, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "tax",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "spread_perc",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "spread",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "effective_rate",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "investment",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=9, scale=3),
        existing_nullable=True,
    )
    op.alter_column(
        "investment",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "investment",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment",
        "liquidation_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "investment_objective",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "start_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "total_tax",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "total_fee",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "net_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "value_change",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "investment_statement",
        "percentage_change",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=9, scale=3),
        existing_nullable=True,
    )
    op.alter_column(
        "investment_statement",
        "index_change",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=9, scale=3),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investment_statement",
        "index_change",
        existing_type=sa.DECIMAL(precision=9, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "investment_statement",
        "percentage_change",
        existing_type=sa.DECIMAL(precision=9, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "investment_statement",
        "value_change",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "investment_statement",
        "net_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "total_fee",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "total_tax",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_statement",
        "start_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "investment_objective",
        "amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "investment",
        "liquidation_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "investment",
        "amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "investment",
        "price",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "investment",
        "quantity",
        existing_type=sa.DECIMAL(precision=9, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "effective_rate",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "spread",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "spread_perc",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "tax",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "perc_tax",
        existing_type=sa.DECIMAL(precision=10, scale=4),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "exchange_rate",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "account_transaction",
        "transaction_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "account_transaction",
        "amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
