"""Change type for float field in credit card transaction  model

Revision ID: 22cec460c931
Revises: c2c5d9d6fa84
Create Date: 2024-10-31 14:09:23.614335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22cec460c931"
down_revision: Union[str, None] = "c2c5d9d6fa84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_card_transaction",
        "transaction_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "credit_card_transaction",
        "dollar_exchange_rate",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "credit_card_transaction",
        "currency_dollar_ex_rate",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "credit_card_transaction",
        "total_tax",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    op.alter_column(
        "credit_card_transaction",
        "total_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_card_transaction",
        "total_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "credit_card_transaction",
        "total_tax",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "credit_card_transaction",
        "currency_dollar_ex_rate",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "credit_card_transaction",
        "dollar_exchange_rate",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "credit_card_transaction",
        "transaction_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
