"""Create model to save indexer series

Revision ID: 5b832f2055b6
Revises: ee073f875441
Create Date: 2024-10-10 22:16:05.932997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b832f2055b6"
down_revision: Union[str, None] = "ee073f875441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "periodicity",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("order", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("edited_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "indexer_series",
        sa.Column("indexer_id", sa.Uuid(), nullable=False),
        sa.Column("indexer_name", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("period", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("periodicity_id", sa.Uuid(), nullable=False),
        sa.Column("periodicity_name", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("edited_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodicity_id"],
            ["periodicity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("indexer_series")
    op.drop_table("periodicity")
    # ### end Alembic commands ###
