"""Add indexer series model

Revision ID: 7e6d1e23b945
Revises: 8cb5acfd36f3
Create Date: 2024-10-18 21:26:50.583691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6d1e23b945'
down_revision: Union[str, None] = '8cb5acfd36f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_series',
    sa.Column('indexer_id', sa.Uuid(), nullable=False),
    sa.Column('indexer_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('periodicity_id', sa.Uuid(), nullable=False),
    sa.Column('periodicity_name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['indexer_id'], ['indexer.id'], ),
    sa.ForeignKeyConstraint(['periodicity_id'], ['periodicity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexer_series')
    # ### end Alembic commands ###
