"""Change names for credit card bill and account statement to 'transaction'

Revision ID: 4f2f2f104724
Revises: 751f0ac68f66
Create Date: 2024-09-30 10:39:13.460799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f2f2f104724'
down_revision: Union[str, None] = '751f0ac68f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('category_id_old', sa.String(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('operation_type', sa.String(length=15), nullable=False),
    sa.Column('transaction_currency_id', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('perc_tax', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('spread_perc', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('effective_rate', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['transaction_currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('credit_card_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category_id_old', sa.String(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('currency_id', sa.String(length=3), nullable=False),
    sa.Column('operation_type', sa.String(length=15), nullable=False),
    sa.Column('transaction_currency_id', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('dollar_exchange_rate', sa.Float(), nullable=True),
    sa.Column('currency_dollar_ex_rate', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('tax_details', sa.JSON(), nullable=True),
    sa.Column('is_installment', sa.Boolean(), nullable=False),
    sa.Column('current_installment', sa.SmallInteger(), nullable=False),
    sa.Column('installments', sa.SmallInteger(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_card.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['credit_card_transaction.id'], ),
    sa.ForeignKeyConstraint(['transaction_currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('credit_card_bill')
    op.drop_table('account_statement')
    op.alter_column('investment', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investment', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('account_statement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency_id', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('category_id_old', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('transaction_currency_id', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('transaction_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('perc_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spread_perc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spread', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effective_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_validated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='account_statement_account_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='account_statement_category_id_fkey'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='account_statement_currency_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_currency_id'], ['currency.id'], name='account_statement_transaction_currency_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_statement_pkey')
    )
    op.create_table('credit_card_bill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credit_card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category_id_old', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('currency_id', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('operation_type', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('transaction_currency_id', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('transaction_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dollar_exchange_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency_dollar_ex_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_installment', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('current_installment', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('installments', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_validated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='credit_card_bill_category_id_fkey'),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_card.id'], name='credit_card_bill_credit_card_id_fkey'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='credit_card_bill_currency_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['credit_card_bill.id'], name='credit_card_bill_parent_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_currency_id'], ['currency.id'], name='credit_card_bill_transaction_currency_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credit_card_bill_pkey')
    )
    op.drop_table('credit_card_transaction')
    op.drop_table('account_transaction')
    # ### end Alembic commands ###
