"""Add Decimal to value in indexer series model

Revision ID: 254ce0707deb
Revises: 3d26bf3e6d4d
Create Date: 2024-12-10 10:08:40.106324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "254ce0707deb"
down_revision: Union[str, None] = "3d26bf3e6d4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indexer_series",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indexer_series",
        "value",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
