"""Add precision to balance model fields

Revision ID: c9eb91aef675
Revises: 6806a52f5ca5
Create Date: 2024-09-25 13:42:20.735300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9eb91aef675'
down_revision: Union[str, None] = '6806a52f5ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_balance', 'previous_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('account_balance', 'incoming',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('account_balance', 'outgoing',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('account_balance', 'transactions',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('account_balance', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_balance', 'balance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('account_balance', 'transactions',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('account_balance', 'outgoing',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('account_balance', 'incoming',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('account_balance', 'previous_balance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
