"""Add balance model

Revision ID: 6806a52f5ca5
Revises: d9ad938959f5
Create Date: 2024-09-25 13:34:54.269780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6806a52f5ca5'
down_revision: Union[str, None] = 'd9ad938959f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balance',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=False),
    sa.Column('incoming', sa.Float(), nullable=False),
    sa.Column('outgoing', sa.Float(), nullable=False),
    sa.Column('transactions', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_balance')
    # ### end Alembic commands ###
