"""Remove investment statement model

Revision ID: 3055c378ec5c
Revises: 0bde2bba385f
Create Date: 2024-09-30 20:18:27.685038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3055c378ec5c'
down_revision: Union[str, None] = '0bde2bba385f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_statement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_statement',
    sa.Column('investment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fee_detail', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('value_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentage_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('index_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], name='investment_statement_investment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='investment_statement_pkey')
    )
    # ### end Alembic commands ###
