"""Add category_old to credit card bill

Revision ID: c66cc083deb0
Revises: 3d8620b9033c
Create Date: 2024-09-24 10:59:54.635559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66cc083deb0'
down_revision: Union[str, None] = '3d8620b9033c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_bill', sa.Column('category_id_old', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_bill', 'category_id_old')
    # ### end Alembic commands ###
