"""Add nullable to code in banck model

Revision ID: c7769b9b7ac4
Revises: 59646f716e38
Create Date: 2024-09-23 21:23:03.844262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7769b9b7ac4'
down_revision: Union[str, None] = '59646f716e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank', 'code',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank', 'code',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
