"""Add field category old to account statement

Revision ID: eb05f92b0493
Revises: c7769b9b7ac4
Create Date: 2024-09-23 22:20:41.885938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb05f92b0493'
down_revision: Union[str, None] = 'c7769b9b7ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_statement', sa.Column('category_id_old', sa.String(), nullable=True))
    op.alter_column('account_statement', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_statement', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('account_statement', 'category_id_old')
    # ### end Alembic commands ###
