"""Change type for amount in credit card model

Revision ID: c2c5d9d6fa84
Revises: 7e6d1e23b945
Create Date: 2024-10-31 14:01:56.590909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2c5d9d6fa84"
down_revision: Union[str, None] = "7e6d1e23b945"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_card_transaction",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_card_transaction",
        "amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
