"""Change type for gross amount in investment statement model

Revision ID: efda8c07479c
Revises: ed2065ffe236
Create Date: 2024-11-02 14:36:37.780629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efda8c07479c"
down_revision: Union[str, None] = "ed2065ffe236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investment_statement",
        "gross_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=15, scale=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investment_statement",
        "gross_amount",
        existing_type=sa.DECIMAL(precision=15, scale=5),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
