"""Update balance model

Revision ID: 6aa0a32c70ab
Revises: 51dddf86a47a
Create Date: 2024-09-25 13:28:52.541175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa0a32c70ab'
down_revision: Union[str, None] = '51dddf86a47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_balance', sa.Column('account_id', sa.Uuid(), nullable=False))
    op.add_column('account_balance', sa.Column('period', sa.Integer(), nullable=False))
    op.add_column('account_balance', sa.Column('previous_balance', sa.Float(), nullable=False))
    op.add_column('account_balance', sa.Column('incoming', sa.Float(), nullable=False))
    op.add_column('account_balance', sa.Column('outgoing', sa.Float(), nullable=False))
    op.add_column('account_balance', sa.Column('transactions', sa.Float(), nullable=False))
    op.add_column('account_balance', sa.Column('balance', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'account_balance', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_balance', type_='foreignkey')
    op.drop_column('account_balance', 'balance')
    op.drop_column('account_balance', 'transactions')
    op.drop_column('account_balance', 'outgoing')
    op.drop_column('account_balance', 'incoming')
    op.drop_column('account_balance', 'previous_balance')
    op.drop_column('account_balance', 'period')
    op.drop_column('account_balance', 'account_id')
    # ### end Alembic commands ###
