"""Adjust fields to correct model

Revision ID: ac52828c00c7
Revises: 8fe28b218519
Create Date: 2025-12-29 21:49:14.228874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac52828c00c7"
down_revision: Union[str, None] = "8fe28b218519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexer", sa.Column("bcb_code", sa.String(length=10), nullable=True))
    op.add_column(
        "indexer", sa.Column("unit_type", sa.String(length=50), nullable=True)
    )
    op.add_column("indexer", sa.Column("source", sa.String(length=100), nullable=True))
    op.drop_column("indexer_series", "unit_type")
    op.drop_column("indexer_series", "bcb_code")
    op.drop_column("indexer_series", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer_series",
        sa.Column(
            "source", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "indexer_series",
        sa.Column(
            "bcb_code", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "indexer_series",
        sa.Column(
            "unit_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("indexer", "source")
    op.drop_column("indexer", "unit_type")
    op.drop_column("indexer", "bcb_code")
    # ### end Alembic commands ###
