"""Added contribution field to investment statement

Revision ID: 3138a0125c10
Revises: 70b7a4a64ee1
Create Date: 2025-10-31 11:36:44.569594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3138a0125c10"
down_revision: Union[str, None] = "70b7a4a64ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_statement",
        sa.Column(
            "contribution",
            sa.Numeric(precision=18, scale=8),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("investment_statement", "contribution")
    # ### end Alembic commands ###
