"""Rename liquidated fields to settled

Revision ID: 70b7a4a64ee1
Revises: 2ea3a6c47b6a
Create Date: 2025-10-29 11:29:52.281783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70b7a4a64ee1"
down_revision: Union[str, None] = "2ea3a6c47b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("investment", "liquidation_date", new_column_name="settlement_date")
    op.alter_column(
        "investment",
        "liquidation_amount",
        new_column_name="settlement_amount",
        existing_type=sa.NUMERIC(precision=15, scale=5),
        type_=sa.Numeric(precision=18, scale=8),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investment",
        "settlement_amount",
        new_column_name="liquidation_amount",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        type_=sa.NUMERIC(precision=15, scale=5),
    )
    op.alter_column("investment", "settlement_date", new_column_name="liquidation_date")
    # ### end Alembic commands ###
