"""Add outgoing field to statement

Revision ID: f41935826d06
Revises: 1b828ac698c5
Create Date: 2025-11-25 23:09:15.328231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f41935826d06"
down_revision: Union[str, None] = "1b828ac698c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_statement",
        sa.Column(
            "outgoing",
            sa.Numeric(precision=18, scale=8),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("investment_statement", "outgoing")
    # ### end Alembic commands ###
