"""new investment models

Revision ID: 31dd14ab810f
Revises: 1312566372db
Create Date: 2025-04-03 12:19:24.522293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31dd14ab810f'
down_revision: Union[str, None] = '1312566372db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_funds_br_statement',
    sa.Column('fund_id', sa.Uuid(), nullable=False),
    sa.Column('contribution', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_amount', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('tax_detail', sa.JSON(), nullable=True),
    sa.Column('fee_detail', sa.JSON(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['investment_funds_br.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_funds_br_statement')
    # ### end Alembic commands ###
