"""Create new funds models

Revision ID: f9edebed4248
Revises: 2eb9b44bbe17
Create Date: 2025-03-18 10:55:19.463170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9edebed4248'
down_revision: Union[str, None] = '2eb9b44bbe17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds_br',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fund_cnpj', sa.String(length=18), nullable=False),
    sa.Column('administrator', sa.String(length=250), nullable=False),
    sa.Column('administrator_cnpj', sa.String(length=18), nullable=False),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('minimum_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('minimum_investment', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('minimum_withdraw', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('initial_investment', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('investment_quotation', sa.String(length=10), nullable=False),
    sa.Column('redemption_quotation', sa.String(length=10), nullable=False),
    sa.Column('redemption_settlement', sa.String(length=10), nullable=False),
    sa.Column('fees', sa.JSON(), nullable=False),
    sa.Column('benchmark', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_funds_br',
    sa.Column('fund_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('investment_quotation_date', sa.Date(), nullable=False),
    sa.Column('liquidation_settlement_date', sa.Date(), nullable=False),
    sa.Column('redemption_quotation_date', sa.Date(), nullable=True),
    sa.Column('redemption_settlement_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('custodian_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('currency_id', sa.String(length=3), nullable=False),
    sa.Column('country_id', sa.String(length=5), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=True),
    sa.Column('is_liquidated', sa.Boolean(), nullable=False),
    sa.Column('tax', sa.JSON(), nullable=True),
    sa.Column('fee', sa.JSON(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['custodian_id'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds_br.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['investment_objective.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['investment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_funds_br')
    op.drop_table('funds_br')
    # ### end Alembic commands ###
