"""Add indexer information and remove unused columns

Revision ID: 8fe28b218519
Revises: f41935826d06
Create Date: 2025-12-29 21:46:17.150921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fe28b218519"
down_revision: Union[str, None] = "f41935826d06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer_series", sa.Column("bcb_code", sa.String(length=10), nullable=False)
    )
    op.add_column(
        "indexer_series", sa.Column("unit_type", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "indexer_series", sa.Column("source", sa.String(length=100), nullable=False)
    )
    op.drop_column("investment_statement", "index_change")
    op.drop_column("investment_statement", "value_change")
    op.drop_column("investment_statement", "percentage_change")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_statement",
        sa.Column(
            "percentage_change",
            sa.NUMERIC(precision=9, scale=3),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "investment_statement",
        sa.Column(
            "value_change",
            sa.NUMERIC(precision=15, scale=5),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "investment_statement",
        sa.Column(
            "index_change",
            sa.NUMERIC(precision=9, scale=3),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("indexer_series", "source")
    op.drop_column("indexer_series", "unit_type")
    op.drop_column("indexer_series", "bcb_code")
    # ### end Alembic commands ###
