"""Rename contribution field to incoming

Revision ID: 1b828ac698c5
Revises: 3138a0125c10
Create Date: 2025-11-25 23:03:22.793679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b828ac698c5"
down_revision: Union[str, None] = "3138a0125c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investment_statement",
        "contribution",
        new_column_name="incoming",
        existing_type=sa.NUMERIC(precision=15, scale=5),
        type_=sa.Numeric(precision=18, scale=8),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investment_statement",
        "incoming",
        new_column_name="contribution",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        type_=sa.NUMERIC(precision=15, scale=5),
    )
    # ### end Alembic commands ###
