"""Adjust fund FK in fund investment statement model

Revision ID: e41692b4316b
Revises: 31dd14ab810f
Create Date: 2025-04-03 22:47:14.611001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41692b4316b'
down_revision: Union[str, None] = '31dd14ab810f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('investment_funds_br_statement_fund_id_fkey', 'investment_funds_br_statement', type_='foreignkey')
    op.create_foreign_key(None, 'investment_funds_br_statement', 'funds_br', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_funds_br_statement', type_='foreignkey')
    op.create_foreign_key('investment_funds_br_statement_fund_id_fkey', 'investment_funds_br_statement', 'investment_funds_br', ['fund_id'], ['id'])
    # ### end Alembic commands ###
