"""Add settlement amount and change is_liquidated to is_settled

Revision ID: 01e8e1286d5b
Revises: e41692b4316b
Create Date: 2025-07-01 19:57:42.182452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01e8e1286d5b"
down_revision: Union[str, None] = "e41692b4316b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_funds_br",
        sa.Column(
            "settlement_amount", sa.Numeric(precision=18, scale=8), nullable=False
        ),
    )
    op.add_column(
        "investment_funds_br", sa.Column("is_settled", sa.Boolean(), nullable=False)
    )
    op.drop_column("investment_funds_br", "is_liquidated")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_funds_br",
        sa.Column("is_liquidated", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("investment_funds_br", "is_settled")
    op.drop_column("investment_funds_br", "settlement_amount")
    # ### end Alembic commands ###
