"""Adjust size from fields in funds model

Revision ID: 1312566372db
Revises: 907f829c206b
Create Date: 2025-03-20 18:43:15.620364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1312566372db'
down_revision: Union[str, None] = '907f829c206b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funds_br', 'investment_quotation',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.alter_column('funds_br', 'redemption_quotation',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.alter_column('funds_br', 'redemption_settlement',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funds_br', 'redemption_settlement',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('funds_br', 'redemption_quotation',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('funds_br', 'investment_quotation',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
