"""Create relation table for indexer and periodicity

Revision ID: c9c1838cf3d6
Revises: 422d419d18a0
Create Date: 2025-12-29 22:20:09.381954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9c1838cf3d6"
down_revision: Union[str, None] = "422d419d18a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexer_periodicity_information",
        sa.Column("indexer_id", sa.Uuid(), nullable=False),
        sa.Column("periodicity_id", sa.Uuid(), nullable=False),
        sa.Column("sgs_code", sa.String(length=10), nullable=True),
        sa.Column("unit", sa.String(length=10), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("edited_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodicity_id"],
            ["periodicity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("indexer", "bcb_code")
    op.drop_column("indexer", "unit_type")
    op.drop_column("indexer", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer",
        sa.Column("source", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "indexer",
        sa.Column(
            "unit_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "indexer",
        sa.Column(
            "bcb_code", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("indexer_periodicity_information")
    # ### end Alembic commands ###
