"""Update investment table with tax and fee columns, rename is_liquidated to is_settled, and adjust numeric precisions

Revision ID: 2ea3a6c47b6a
Revises: 49067a5c172f
Create Date: 2025-10-29 10:58:41.900661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ea3a6c47b6a"
down_revision: Union[str, None] = "49067a5c172f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("investment", sa.Column("tax", sa.JSON(), nullable=True))
    op.add_column("investment", sa.Column("fee", sa.JSON(), nullable=True))
    op.alter_column("investment", "is_liquidated", new_column_name="is_settled")
    op.alter_column(
        "investment",
        "price",
        existing_type=sa.NUMERIC(precision=15, scale=5),
        type_=sa.Numeric(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "investment",
        "quantity",
        existing_type=sa.NUMERIC(precision=9, scale=3),
        type_=sa.Numeric(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "investment",
        "amount",
        existing_type=sa.NUMERIC(precision=15, scale=5),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("investment", "is_settled", new_column_name="is_liquidated")
    op.alter_column(
        "investment",
        "amount",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.NUMERIC(precision=15, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "investment",
        "quantity",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.NUMERIC(precision=9, scale=3),
        nullable=True,
    )
    op.alter_column(
        "investment",
        "price",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.NUMERIC(precision=15, scale=5),
        nullable=True,
    )
    op.drop_column("investment", "fee")
    op.drop_column("investment", "tax")
    # ### end Alembic commands ###
