"""Update created_at with server deafult

Revision ID: 422d419d18a0
Revises: ac52828c00c7
Create Date: 2025-12-29 22:01:55.512255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "422d419d18a0"
down_revision: Union[str, None] = "ac52828c00c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Account tables
    op.alter_column(
        "account",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "account_transaction",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "account_balance",
        "created_at",
        server_default=sa.text("now()"),
    )

    # Core tables
    op.alter_column(
        "currency",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "category",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "expense_type",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "category_expense_user",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "country",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "bank",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "indexer_type",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "indexer",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "indexer_series",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "liquidity",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "periodicity",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "tax_fee",
        "created_at",
        server_default=sa.text("now()"),
    )

    # Credit Card tables
    op.alter_column(
        "credit_card",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "credit_card_transaction",
        "created_at",
        server_default=sa.text("now()"),
    )

    # Investment tables
    op.alter_column(
        "investment_funds_br",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "investment_funds_br_statement",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "investment_category",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "investment_type",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "investment_objective",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "funds_br",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "investment",
        "created_at",
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "investment_statement",
        "created_at",
        server_default=sa.text("now()"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
