"""Add currency to statement model

Revision ID: e34ea7f073e7
Revises: b0c959236e20
Create Date: 2026-04-06 09:42:39.391431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e34ea7f073e7"
down_revision: Union[str, None] = "b0c959236e20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investment_statement",
        sa.Column(
            "currency_id", sa.String(length=3), nullable=False, server_default="BRL"
        ),
    )
    op.create_foreign_key(
        None, "investment_statement", "currency", ["currency_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "investment_statement", type_="foreignkey")
    op.drop_column("investment_statement", "currency_id")
    # ### end Alembic commands ###
