extend type Query {
    getAccounts(params: GetAccountsInput): GetAccountResponse
    getAccountBalance(params: GetAccountBalanceInput): GetAccountBalanceResponse
}

# Account schemas
input GetAccountsInput {
    accountId: String
    currencyId: String
    active: Boolean
}

type GetAccountResponse {
    quantity: Int!
    accounts: [Account]!
}

type Account {
    accountId: ID!
    active: Boolean!
    bankId: String!
    nickname: String!
    description: String
    branch: String
    number: String
    openDate: String
    closeDate: String
    typeId: String!
    currencyId: String!
    # credit cards
}

# Account balance schemas
input GetAccountBalanceInput {
    accountId: String!
    period: Int!
}

type GetAccountBalanceResponse {
    quantity: Int!
    accountName: String!
    balance: [AccountBalance]!
}

type AccountBalance {
    period: Int!
    previousBalance: Float!
    incoming: Float!
    outgoing: Float!
    transactions: Float!
    earnings: Float!
    balance: Float!
}
