extend type Query {
    getAccounts(params: GetAccountsInput): GetAccountResponse
    getAccountTransactions(params: GetAccountTransactionInput): GetAccountTransactionResponse
    getAccountBalance(params: GetAccountBalanceInput): GetAccountBalanceResponse
}

extend type Mutation {
    createAccountTransaction(transaction: CreateAccountTransactionInput): CreateUpdateAccountTransactionResponse
    updateAccountTransaction(transaction: UpdateAccountTransactionInput): CreateUpdateAccountTransactionResponse
}

# Account schemas
input GetAccountsInput {
    accountId: String
    currencyId: String
    active: Boolean
}

type GetAccountResponse {
    quantity: Int!
    accounts: [Account]!
}

type Account {
    accountId: ID!
    active: Boolean!
    bankId: String!
    nickname: String!
    description: String
    branch: String
    number: String
    openDate: String
    closeDate: String
    typeId: String!
    currencyId: String!
    currencySymbol: String!
    # credit cards
}

# Account transactions schemas
input GetAccountTransactionInput {
    accountId: String
    startPeriod: Int
    endPeriod: Int
}


type GetAccountTransactionResponse {
    quantity: Int!
    transactions: [AccountTransaction]!
}


input CreateAccountTransactionInput {
    transactionId: Int
    accountId: String!
    currencyId: String!
    amount: Float!
    transactionDate: String!
    categoryId: String!
    description: String
    transactionCurrencyId: String
    transactionAmount: Float
    exchangeRate: Float
    taxPerc: Float
    tax: Float
    spreadPerc: Float
    spread: Float
    effectiveRate: Float
    origin: String
    isValidated: Boolean
}


input UpdateAccountTransactionInput {
    # Update is the same as create, but without any field required, except transactionId
    transactionId: Int
    accountId: String
    currencyId: String
    amount: Float
    transactionDate: String
    categoryId: String
    description: String
    transactionCurrencyId: String
    transactionAmount: Float
    exchangeRate: Float
    taxPerc: Float
    tax: Float
    spreadPerc: Float
    spread: Float
    effectiveRate: Float
    origin: String
    isValidated: Boolean
}

type CreateUpdateAccountTransactionResponse {
    transaction: AccountTransaction
}

type AccountTransaction {
    transactionId: ID!
    ownerId: String!
    accountId: String!
    accountNickname: String
    period: Int!
    currencyId: String!
    currencySymbol: String
    amount: Float!
    transactionDate: String!
    categoryId: String
    categoryName: String
    description: String
    transactionCurrencyId: String
    transactionAmount: Float
    exchangeRate: Float
    taxPerc: Float
    tax: Float
    spreadPerc: Float
    spread: Float
    effectiveRate: Float
}

# Account balance schemas
input GetAccountBalanceInput {
    accountId: String!
    period: Int!
}

type GetAccountBalanceResponse {
    quantity: Int!
    accountName: String!
    balance: [AccountBalance]!
}

type AccountBalance {
    period: Int!
    previousBalance: Float!
    incoming: Float!
    outgoing: Float!
    transactions: Float!
    earnings: Float!
    balance: Float!
}
