extend type Query {
    getCreditCards(params: GetCreditCardsInput): GetCreditCardsResponse
    getCreditCardInstallmentDueDates(params: GetInstallmentsDueDatesInput): GetInstallmentsDueDatesResponse
}

# Get credit cards
input GetCreditCardsInput {
    id: String
    active: Boolean
}

type GetCreditCardsResponse {
    quantity: Int!
    creditCards: [CreditCard]!
}

type CreditCard {
    creditCardId: String!
    active: Boolean!
    ownerId: String!
    nickname: String!
    accountId: String
    currencyId: String!
    issueDate: Date
    cancellationDate: String
    dueDate: Int
    closeDay: Int
}

# Credit card installments
input GetInstallmentsDueDatesInput {
    creditCardId: String!
    totInstallments: Int!
    transactionDate: Date!
}

type GetInstallmentsDueDatesResponse {
    dueDates: [InstallmentsDueDates]!
}

type InstallmentsDueDates {
    currentInstallment: Int!
    dueDate: Date!
}