extend type Query {
    getHelloWorld: String
    getIndexerSeries(params: GetIndexerSeriesInput! ): GetIndexerSeriesResponse
    getCurrencies: GetCurrenciesResponse
}

extend type Mutation {
    _empty: String
}

# Indexer series schemas
input GetIndexerSeriesInput {
    indexerId: String!
    periodicityId: String
    startPeriod: Int
    endPeriod: Int
}

type GetIndexerSeriesResponse {
    quantity: Int!,
    series: [IndexerSeries]
}

type IndexerSeries {
    id: ID!
    indexerId: String!
    indexerName: String
    date: String
    period: Int
    value: Float
    periodicityId: String!
    periodicityName: String
    unit: String
}

# Currency schemas
type GetCurrenciesResponse {
    quantity: Int!
    currencies: [Currency]!
}

type Currency {
    currencyId: ID!
    name: String!
    symbol: String!
}