extend type Query {
    getInvestments(params: GetInvestmentsRequest): GetInvestmentsResponse
    getInvestmentStatements(params: GetInvestmentStatementRequest): GetInvestmentStatementResponse
}

input GetInvestmentsRequest {
    investmentId: String
    startDate: String
    endDate: String
    isSettled: Boolean
}

type GetInvestmentsResponse {
    quantity: Int!
    investments: [Investment]!
}

type Investment {
    investmentId: String!
    custodianId: String!
    accountId: String
    name: String!
    typeId: String!
    transactionDate: Date!
    maturityDate: String
    quantity: Float!
    price: Float!
    amount: Float!
    contractedRate: String
    currencyId: String!
    currencySymbol: String
    indexerTypeId: String!
    indexerTypeName: String
    indexerId: String!
    indexerName: String!
    liquidityId: String!
    liquidityName: String!
    isSettled: Boolean!
    settlementDate: String
    settlementAmount: Float
    countryId: String!
    countryName: String
    observation: String
    objectiveId: String
}


input GetInvestmentStatementRequest {
    investmentId: String!
    startDate: String
    endDate: String
    period: Int
}

type GetInvestmentStatementResponse {
    quantity: Int!
    statement: [InvestmentStatement]!
}

type InvestmentStatement {
    investmentStatementId: String!
    ivnestmentId: String!
    period: Int!
    previousAmount: Float!
    grossAmount: Float!
    totalTax: Float!
    totalFee: Float!
    referenceDate: String!
    atMaturity: Boolean!
    valueChange: Float
    percentageChange: Float
    netAmount: Float!
}