# This file contains the schemas for genral Investment functions that aggreagates all
#   investment types

extend type Query {
    getInvestmentPerformance(params: GetInvestmentPerformanceInput): GetInvestmentPerformanceResponse
    getStatementMetadata(params: GetStatementMetadataInput): GetStatementMetadataResponse
}

extend type Mutation {
    createInvestmentStatement(statement: CreateInvestmentStatementInput): CreateInvestmentStatementResponse
    updateInvestmentStatement(statement: UpdateInvestmentStatementInput): UpdateInvestmentStatementResponse
}


# Performance Schemas
input GetInvestmentPerformanceInput {
    investmentId: String
}

type GetInvestmentPerformanceResponse {
    xLabel: [String]! 
    data: [LineChartSeries!]!
}


#  Statement Schemas
input TaxFeeDetail {
    taxFeeId: String!
    amount: Float!
    currencyId: String!
}

input CreateInvestmentStatementInput {
    investmentId: String!
    period: Int!
    contribution: Float!
    referenceDate: Date!
    grossAmount: Float!
    netAmount: Float!
    taxDetail: [TaxFeeDetail]
    feeDedtail: [TaxFeeDetail]
}

type CreateInvestmentStatementResponse {
    created: Boolean!
    statementId: String!
}


input UpdateInvestmentStatementInput {
    statementId: String!
    contribution: Float
    grossAmount: Float
    netAmount: Float
    taxDetail: [TaxFeeDetail]
    feeDedtail: [TaxFeeDetail]
}

type UpdateInvestmentStatementResponse {
    updated: Boolean!
    statementId: String!
}

input GetStatementMetadataInput {
    investmentId: String!
}

type GetStatementMetadataResponse {
    period: Int!
    referenceDate: Date!
}